### ISSUE TITLE
Support for class inheritance

### ISSUE THREAD

**Issue by aemadrid** [emmanuel/aequitas#2]
It seems that aequitas does not support class inheritance. I was expecting class B to inherit class A rules. Is this something planned for the future?

```
[1] pry(main)> class A
[1] pry(main)*   include Aequitas  
[1] pry(main)*   attr_accessor :name  
[1] pry(main)*   validates_presence_of :name  
[1] pry(main)* end  
=> #<Aequitas::ContextualRuleSet rule_sets={:default=>#<7f656317Aequitas::RuleSet {%<Aequitas::Rule::Presence::NotBlank attribute_name=:name custom_message=nil guard=#<Aequitas::Rule::Guard if_test=nil unless_test=nil> skip_condition=#<Aequitas::Rule::SkipCondition allow_nil=nil allow_blank=nil>>}>}>
[2] pry(main)> 
[3] pry(main)> class B < A
[3] pry(main)*   attr_accessor :age  
[3] pry(main)*   validates_presence_of :age  
[3] pry(main)* end  
NameError: undefined local variable or method `rules' for #<Aequitas::ContextualRuleSet:0x66788a7b>
from /Users/some_user/.rvm/gems/jruby-1.6.5@orientdb_model/bundler/gems/aequitas-e158693570e2/lib/aequitas/contextual_rule_set.rb:114:in `concat'
```

**Comment by emmanuel** [comment]
Thanks for the report. This is an oversight, class inheritance is certainly planned.

**Comment by emmanuel** [comment]
Class inheritance was previously working... I had done some refactoring (variable renaming) without test coverage (I know... shame on me), which led to me introducing this bug. This was caused by a typo in the `ContextualRuleSet#concat` method: @azimux fixed this in #3.

I'm working on the test suite to get more coverage built up. I hope to not make stupid mistakes like this in the future ;)

**Comment by aemadrid** [comment]
I've done my fair share of stupid mistaks and I keep making them ;-) Thanks for the update.

**Comment by mbj** [comment]
@aq1018 Development under this repository stopped and moved to mbj/aequitas. It was totally rewritten so you might take a look. A release is still pending there also ;)

**Comment by aq1018** [comment]
ahh... Thanks!

**Comment by aq1018** [comment]
@emmanuel do you mind making a note in your readme indicating that the repo has moved?

**Comment by mbj** [comment]
@emmanuel As I have commit access I replaced the readme with the development moved message.
