### ISSUE TITLE
Feature Request: Custom Validators

### ISSUE THREAD

**Issue by indrekj** [emmanuel/aequitas#6]
I read the source code, but didn't find an easy way to add custom validators to my app.

It would be cool if we could do something like this:

``` ruby
# checks if latitude and longitude are valid
validates_with Validators::GeoLocation

# or
validates :latitude, :with => Validators::Latitude
```

**Comment by mbj** [comment]
With my context free branch you can workaround the missing DSL primitive this way:

``` ruby
class Valdidator
  include Aequitas
  rule_set << YourValidation.new
end
```

**Comment by mbj** [comment]
Should also work with master!
