### ISSUE TITLE
Multiple validations for one model

### ISSUE THREAD

**Issue by greyblake** [emmanuel/aequitas#7]
I am not aware about Aequitas design, so I wonder: is it possible to specify validations the way, so I can define in runtime which validation rules should be used for current model?

Example:

We have model `User`.
We have to validation sets: `UserValidation` and `AdminValidation`.
In some cases I want `UserValidation` to be used in other I want to use `AdminValidation`.

Thanks.

**Comment by mbj** [comment]
I normally create external validators for this, see this [gist](https://gist.github.com/3150074).

**Comment by greyblake** [comment]
Thanks @mbj.
So if I wanna have ability to use different validations(which one to use I decide in runtime) for `user` I should implement validation setter to change validaton object on `user`?

**Comment by mbj** [comment]
``` ruby
class AdminValidator < ExternalValidator
  validates_stuff_for_admin
end
class UserValidator < ExternalValidator
  validates_stuff_for_user
end

# External decision
user = User.new
validation = AdminValidator.new(user)
validation.valid?

validation = UserValidator.new(user)
validation.valid?

# Internal decision
class User
  def validation_for_state
    if user?
       UserValidator
    else
      AdminValidator
    end.new(self)
  end
end

user = User.new
user.validator_for_state.valid?
```

The whole thing is just about to decide which class to create an object from.  The decision can be done at any appropriate place.

**Comment by greyblake** [comment]
That's cool! Thanks!

**Comment by mbj** [comment]
@greyblacke, fwiw: A setter for validator is the worst option IMHO.

**Comment by mbj** [comment]
@greyblake, I'd like to document the fact we can easily use external validators with aequitas, in case you cleanup my gist (I never ran it), can you create a pull request for the Readme? I'll merge it in.

**Comment by greyblake** [comment]
Actually I haven't try it yet.
Ok, I'll do it as soon as I have free time(most likely on weekends).
Can you assign this on me so I won't forget?

**Comment by mbj** [comment]
I cannot assign an issue to someone who does not have commit access to this repo. Why dont you create an "empty" pull request, GH will track it for you mostly like an issue.

As this is not my repo, I cannot decide on giving commit access.

**Comment by greyblake** [comment]
@mbj , Looks like the external validation doesn't work as I expected:

``` ruby
require 'rubygems'

require 'virtus'
require 'aequitas'

class User
  include Virtus
  include Aequitas
  attribute :login, String
  validates_presence_of :login
end


class UserValidator
  include Aequitas
  validates_presence_of :login

  def initialize(object)
    @object = object
  end

  def method_missing(name,*args,&block)
    super if args.length != 0
    @object[name]
  end
end


user = User.new(:login => "Sirin")
validator = UserValidator.new(user)

user.valid?      # => true
validator.valid? # => false, EXPECTED TO BE TRUE
validator.login  # => "Sirin"

```

Did I do something wrong?

**Comment by mbj** [comment]
I just [pushed](https://github.com/mbj/aequitas/commit/40e7585890e73cbaefc7721f0c1c6a2b462b930c) a `Aequitas::External` mixin you can use to build external validators without the method missing stuff and own initializer.

This code did not land in emanuel/aequitas for now.

From just staring at the code I do not see something "wrong" here. In case you create an runnable gist I'm happy to debug. But you can also try with my commit I referenced above.

Edit: Markdown.

**Comment by mbj** [comment]
@greyblake You might be interested into `mbj/aequitas` and the `context-free` branch. It does only allow external validators, and the spec coverage is much higher.

**Comment by mbj** [comment]
I'll close this issue since the code ended in a repo.

**Comment by greyblake** [comment]
@mjb. I'll try it as I have some free time.
